name: Unit Tests # name of the test

on:
 push:
   branches: [ main ] 
 pull_request:
   branches: [ main ] 

jobs: # the things being executed
 tests:
   runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
   env:
      CI: false
      REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
      REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
      REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
   steps:
     - uses: actions/checkout@v4 # using version 4 of Actions
     - name: Install Dependencies
       run: |
        cd triton-eats/client
        npm install
     - name: Unit Test
       run: |
        cd triton-eats/client
        npm test # the actual testing line
